#[derive(Debug, Clone)]
pub enum Message {
  ScrollChanged(f32),
  WindowResized(f32, f32),
  Click(f32, f32),
  NavigateTo(String),
  LoadUrl(usize, String),
  HtmlFetched(usize, String, bool, Result<String, String>),
  CssFetched(usize, Vec<String>),
  AddressInputChanged(String),
  NewTab,
  SwitchTab(usize),
  GoBack,
  GoForward,
  TitleBarPressed,
  MinimizeWindow,
  ToggleMaximizeWindow,
  CloseWindow,
  CloseTab(usize),
  TabHovered(usize),
  TabUnhovered,
  ScrollToFragment(String),
  ToggleBookmark,
}
