[package]
name    = "agr-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "agr"
path = "src/main.rs"

[dependencies]
net    = { path = "../net" }
html-parser   = { path = "../html-parser" }
css-parser = { path = "../css-parser" }
layout = { path = "../layout" }
js-bindings = {path = "../js-bindings"}
iced       = { workspace = true }
tokio      = { workspace = true }